# ######################### #
# 此配置文件是【开发环境】的配置 #
#  此配置文件需要被激活才会生效 #
# ######################## #

# 服务端口
server:
  port: 9081

# 连接数据库的配置参数
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ams?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

# 日志的显示级别
logging:
  level:
    cn.tedu.csmall: trace
#JWT相关配置
csmall:
  jwt:
    secret-key: a9F8ujGDhjgFvfEd3SA90ukDS
    duration-in-minute: 14400